cp ./themes/* ./Moon/theme
cp ./themes/* ./Extragalactic/theme
cp ./themes/* ./Planets/theme
cp ./themes/* ./Galactic/theme
cp ./themes/* ./AstroClub/theme
cp ./themes/* ./TheSky/theme
cp ./themes/* ./MiscSolSys/theme
cp ./themes/* ./Comets/theme
cp ./themes/* ./ObservatoryPics/theme
cp ./themes/* ./MDMRun/theme
cp ./themes/* ./BEST/theme
