cp -f ./TheSky/theme/style.css ./Moon/theme
cp -f ./TheSky/theme/style.css ./Extragalactic/theme
cp -f ./TheSky/theme/style.css ./Planets/theme
cp -f ./TheSky/theme/style.css ./Galactic/theme
cp -f ./TheSky/theme/style.css ./AstroClub/theme
cp -f ./TheSky/theme/style.css ./TheSky/theme
cp -f ./TheSky/theme/style.css ./theme
cp -f ./TheSky/theme/style.css ./Comets/theme
cp -f ./TheSky/theme/style.css ./ObservatoryPics/theme
